"""Updated posts

Revision ID: 8afed7e362c2
Revises: fdad3a8d8731
Create Date: 2021-02-10 12:33:38.626097

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8afed7e362c2'
down_revision = 'fdad3a8d8731'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('competitionEnd', sa.DateTime(), nullable=True))
    op.add_column('posts', sa.Column('competitionWinners', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'competitionWinners')
    op.drop_column('posts', 'competitionEnd')
    # ### end Alembic commands ###
