"""Added points and place to images

Revision ID: 77aa96d71b6f
Revises: 8afed7e362c2
Create Date: 2021-02-23 14:14:12.078083

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '77aa96d71b6f'
down_revision = '8afed7e362c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('place', sa.Integer(), nullable=True))
    op.add_column('images', sa.Column('points', sa.Integer(), nullable=True))
    op.drop_column('posts', 'competitionWinners')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('competitionWinners', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('images', 'points')
    op.drop_column('images', 'place')
    # ### end Alembic commands ###
