"""Added judge column to posts

Revision ID: d7c8e4f42a66
Revises: 77aa96d71b6f
Create Date: 2021-02-23 14:58:36.678623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7c8e4f42a66'
down_revision = '77aa96d71b6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('judged', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'judged')
    # ### end Alembic commands ###
